### ISSUE TITLE
Change casing in package references.

### ISSUE THREAD

**Issue by robvanpamel** [rebus-org/Rebus.Autofac#1]
Hi, 

Could you change line 50 in https://github.com/rebus-org/Rebus.Autofac/blob/master/Rebus.Autofac/Rebus.Autofac.csproj  to use the correct casing. 
If you are using .NET Core with project.json files this causes an issue that **r**ebus cannot be found (since it should be **R**ebus)

Before:

    <ItemGroup>

        <PackageReference Include="rebus" Version="4.0.0-b05" />

        <PackageReference Include="Autofac" Version="4.4.0" />

    </ItemGroup>

After: 

     <ItemGroup>

        <PackageReference Include="Rebus" Version="4.0.0-b05" />

        <PackageReference Include="Autofac" Version="4.4.0" />

    </ItemGroup>

Thanks

**Comment by mookid8000** [comment]
I don't think this is a problem anymore 😄
