### ISSUE TITLE
Failed message handling invoked twice the handler

### ISSUE THREAD

**Issue by clegendre** [rebus-org/Rebus.Autofac#18]
https://github.com/rebus-org/Rebus.Autofac/blob/0474cabe3d887c5cc1fa81d9e228ae5bd9ddbb98/Rebus.Autofac/Autofac/AutofacHandlerActivator.cs#L132

This line should not include the message type itself, since line below already does. `GetBaseTypes(includeSelf: false)` should fix this issue.

**Comment by mookid8000** [comment]
It's fixed in Rebus.Autofac 6.0.0, which is on NuGet.org now. 🙂 

Thanks for reporting this and suggesting a fix! I did exactly what you proposed 👍
