### ISSUE TITLE
Autofac 6.x and later are not CLS compliant

### ISSUE THREAD

**Issue by kendallb** [rebus-org/Rebus.Autofac#22]
I tried to upgrade to the latest packaged and it fails:

https://github.com/autofac/Autofac/issues/1255

Perhaps the solution is to mark this project itself as also not being CLS compliant?

**Comment by mookid8000** [comment]
> Perhaps the solution is to mark this project itself as also not being CLS compliant?

Could be.... but, is Rebus (the core DLL) even marked as CLS compliant?

**Comment by kendallb** [comment]
Yeah not sure exactly where the error is coming from but it’s a know issue wit Autofac 6.x and later.

**Comment by mookid8000** [comment]
OK, I realize now that the solution is to delete the Properties folder alltogether 😁 just a sec

**Comment by mookid8000** [comment]
I've released Rebus.Autofac 7.1.0 now 🙂

**Comment by kendallb** [comment]
👍

**Comment by kendallb** [comment]
Well now we get warnings when building against the latest Rebus for other projects, not just Autofac :(. Probably should put that back and find another solution for this library? Keeping the Autofac dependency < 6.0 will at least avoid it for the moment.

https://github.com/rebus-org/Rebus/issues/947

**Comment by mookid8000** [comment]
I've put the CLS compliance attribute thing back into Rebus – it got lost some time around version 6.5.2

Rebus 6.5.3 has the attribute!
