### ISSUE TITLE
New Rebus Autofac - could not be dispatched to any handlers

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus.Autofac#5]
A little late to the game but updated my nuget packages and got a new Rebus Autofac.
Is there a new way to register the handlers ?

This was how I did it before:
//_builder.RegisterAssemblyTypes(typeof(HeartBeatCommandHandler).Assembly)
// .Where(x => typeof(IHandleMessages).IsAssignableFrom(x))
// .AsClosedTypesOf(typeof(IHandleMessages<>))
// .AsImplementedInterfaces()
// .InstancePerDependency()
// .PropertiesAutowired();

But now I'm getting ...could not be dispatched to any handlers.

**Comment by ben-jacobs** [comment]
This is how I'm doing it in the current version.

builder.RegisterAssemblyTypes(typeof(Program).Assembly)
                                .Where(t => t.GetInterfaces()
                                     .Any(i => i.IsAssignableFrom(typeof(IHandleMessages<>)))) //&& !i.IsAbstract
                                .AsImplementedInterfaces()
                                .InstancePerDependency()
                                .PropertiesAutowired();

**Comment by mookid8000** [comment]
Rebus.Autofac 5.2.0 now has a couple of registration extensions on `ContainerBuilder`, enabling registration of a single handler type:
```csharp
builder.RegisterHandler<MyMessageHandler>();
```
or all handler from an entire assembly:
```csharp
builder.RegisterHandlersFromAssemblyOf<MyMessageHandler>();
```
It's out in a few minutes 🙂 

I have verified that the registration helpers work as intended in [this test](https://github.com/rebus-org/Rebus.Autofac/blob/master/Rebus.Autofac.Tests/TestRegistrationApi.cs)
